// Do Not Edit; Auto Generated by the 'content' package

package staticContent

const Struct_html = `<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Edit a struct</title>
</head>
<body>
<form>
    <label>Field:
        <input type="text" name="field">
    </label>
</form>
</body>
</html>`
